

export const customerGroups = [
  {
    id: 1,
    name: 'VIP Customers',
    description: 'High-value customers with premium benefits',
    type: 'VIP',
    customers: 356,
    orders: 423,
    totalSpent: 125430.50,
    status: 'active',
    createdAt: '2024-05-20',
    icon: '⭐',
    iconBg: 'bg-yellow-100 text-yellow-600',
  },
  {
    id: 2,
    name: 'Loyal Customers',
    description: 'Customers with repeat purchases',
    type: 'Loyalty',
    customers: 1245,
    orders: 832,
    totalSpent: 98210.75,
    status: 'active',
    createdAt: '2024-05-18',
    icon: '☆',
    iconBg: 'bg-blue-100 text-blue-600',
  },
  {
    id: 3,
    name: 'Wholesale Buyers',
    description: 'Bulk buyers and resellers',
    type: 'Wholesale',
    customers: 234,
    orders: 556,
    totalSpent: 76480.00,
    status: 'active',
    createdAt: '2024-05-15',
    icon: '🏪',
    iconBg: 'bg-purple-100 text-purple-600',
  },
  {
    id: 4,
    name: 'New Customers',
    description: 'Recently registered customers',
    type: 'Default',
    customers: 1289,
    orders: 372,
    totalSpent: 28750.20,
    status: 'active',
    createdAt: '2024-05-10',
    icon: '🎁',
    iconBg: 'bg-green-100 text-green-600',
  },
  {
    id: 5,
    name: 'Discount Seekers',
    description: 'Customers who use discounts frequently',
    type: 'Behavioral',
    customers: 842,
    orders: 301,
    totalSpent: 18460.30,
    status: 'inactive',
    createdAt: '2024-05-08',
    icon: '%',
    iconBg: 'bg-orange-100 text-orange-600',
  },
  {
    id: 6,
    name: 'Local Customers',
    description: 'Customers from local region',
    type: 'Segment',
    customers: 567,
    orders: 412,
    totalSpent: 22840.10,
    status: 'active',
    createdAt: '2024-05-05',
    icon: '📍',
    iconBg: 'bg-teal-100 text-teal-600',
  },
  {
    id: 7,
    name: 'Abandoned Cart',
    description: 'Customers with abandoned carts',
    type: 'Behavioral',
    customers: 193,
    orders: 74,
    totalSpent: 7620.00,
    status: 'inactive',
    createdAt: '2024-05-02',
    icon: '🛒',
    iconBg: 'bg-red-100 text-red-600',
  },
  {
    id: 8,
    name: 'Corporate Clients',
    description: 'Business and corporate accounts',
    type: 'Corporate',
    customers: 100,
    orders: 275,
    totalSpent: 9120.45,
    status: 'active',
    createdAt: '2024-04-28',
    icon: '🏢',
    iconBg: 'bg-slate-100 text-slate-600',
  },
  {
    id: 9,
    name: 'Inactive Customers',
    description: 'Customers inactive for 90+ days',
    type: 'Behavioral',
    customers: 1102,
    orders: 64,
    totalSpent: 0.00,
    status: 'inactive',
    createdAt: '2024-04-20',
    icon: '⏸',
    iconBg: 'bg-slate-100 text-slate-500',
  },
  {
    id: 10,
    name: 'Premium Members',
    description: 'Members with premium subscription',
    type: 'VIP',
    customers: 98,
    orders: 236,
    totalSpent: 12931.90,
    status: 'active',
    createdAt: '2024-04-15',
    icon: '🏅',
    iconBg: 'bg-amber-100 text-amber-600',
  },
  {
    id: 11,
    name: 'International Buyers',
    description: 'Customers from outside the country',
    type: 'Segment',
    customers: 156,
    orders: 200,
    totalSpent: 8420.60,
    status: 'active',
    createdAt: '2024-04-10',
    icon: '✈',
    iconBg: 'bg-cyan-100 text-cyan-600',
  },
  {
    id: 12,
    name: 'Default Group',
    description: 'All customers by default',
    type: 'Default',
    customers: 4826,
    orders: 2745,
    totalSpent: 386745.20,
    status: 'active',
    createdAt: '2024-01-01',
    icon: '👤',
    iconBg: 'bg-blue-100 text-blue-500',
  },
];

export const customerGroupStats = {
  totalGroups:    { count: 12,       label: 'Active groups' },
  totalCustomers: { count: 4826,     label: 'In all groups' },
  totalOrders:    { count: 2745,     label: 'From group members' },
  totalSpent:     { value: 386745.20, label: 'From group members' },
};
